export enum localInstrument {
  MANU = 0,
  DICT = 1,
  QRES = 2,
  QRDN = 3,
  INIC = 6,
}

export enum PersonType {
  PESSOA_NATURAL = 0,
  PESSOA_JURIDICA = 1,
}

export enum PaymentPriorityType {
  PRIORITY = 0,
  ANALYSIS = 1,
  SCHEDULED = 2,
}

export enum PaymentStatusType {
  RCVD = 'RCVD',
  CANC = 'CANC',
  ACCP = 'ACCP',
  ACPD = 'ACPD',
  RJCT = 'RJCT',
  ACSC = 'ACSC',
  PDNG = 'PDNG',
  SCHD = 'SCHD',
}

export enum AccountPaymentsType {
  CACC = 0,
  SVGS = 2,
}

export enum EnumRejectionReason {
  SALDO_INSUFICIENTE = 'SALDO_INSUFICIENTE',
  VALOR_ACIMA_LIMITE = 'VALOR_ACIMA_LIMITE',
  VALOR_INVALIDO = 'VALOR_INVALIDO',
  COBRANCA_INVALIDA = 'COBRANCA_INVALIDA',
  NAO_INFORMADO = 'NAO_INFORMADO',
  PAGAMENTO_DIVERGENTE_CONSENTIMENTO = 'PAGAMENTO_DIVERGENTE_CONSENTIMENTO',
  DETALHE_PAGAMENTO_INVALIDO = 'DETALHE_PAGAMENTO_INVALIDO',
  PAGAMENTO_RECUSADO_DETENTORA = 'PAGAMENTO_RECUSADO_DETENTORA',
  PAGAMENTO_RECUSADO_SPI = 'PAGAMENTO_RECUSADO_SPI',
  FALHA_INFRAESTRUTURA = 'FALHA_INFRAESTRUTURA',
  FALHA_INFRAESTRUTURA_SPI = 'FALHA_INFRAESTRUTURA_SPI',
  FALHA_INFRAESTRUTURA_DICT = 'FALHA_INFRAESTRUTURA_DICT',
  FALHA_INFRAESTRUTURA_ICP = 'FALHA_INFRAESTRUTURA_ICP',
  FALHA_INFRAESTRUTURA_PSP_RECEBEDOR = 'FALHA_INFRAESTRUTURA_PSP_RECEBEDOR',
  FALHA_INFRAESTRUTURA_DETENTORA = 'FALHA_INFRAESTRUTURA_DETENTORA',
  CONTAS_ORIGEM_DESTINO_IGUAIS = 'CONTAS_ORIGEM_DESTINO_IGUAIS',
  FALHA_AGENDAMENTO_PAGAMENTOS = 'FALHA_AGENDAMENTO_PAGAMENTOS',
}

export enum AuthorisationStatusType {
  AWAITING_AUTHORISATION,
  AUTHORISED,
  REJECTED,
  CONSUMED,
  PARTIALLY_ACCEPTED,
}
